name: Static Code Analysis with Compilation

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  static-analysis:
    name: Run Static Code Analysis
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Step 3: Compile the code
    - name: Compile the code
      run: javac src/main/java/com/example/todo/*.java

    # Step 4: Download Checkstyle
    - name: Download Checkstyle
      run: wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar -O checkstyle.jar

    # Step 5: Run Checkstyle on Java code
    - name: Run Checkstyle
      run: java -jar checkstyle.jar -c /google_checks.xml src/main/java
