name: Static Code Analysis

on:
  pull_request:
    branches:
      - main
      - dev  # Add other branches if needed
  push:
    branches:
      - main
      - dev

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    # Step 3: Install Checkstyle
    - name: Download Checkstyle
      run: wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.0/checkstyle-10.12.0-all.jar -O checkstyle.jar

    # Step 4: Run Checkstyle
    - name: Run Checkstyle
      run: java -jar checkstyle.jar -c /google_checks.xml src/main/java

    # Step 5: Archive Checkstyle Reports (optional)
    - name: Upload Checkstyle Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-results
        path: checkstyle-result.xml
